name: Build & Run Test Suite (macOS)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LLVM and python
      run: sudo brew install llvm@10.0.0_3 python

    - name: Build the compiler and run the test suite
      run: |
        cd cdotc/utils
        ./build_script --test
